const $ = (s, root = document) => root.querySelector(s);
const app = $('#app');
const overlay = $('#overlay');
const NS = 'echo.ming1566.cinema.v1';
const names = {jiajing:'嘉靖',hairui:'海瑞',yansong:'严嵩',xujie:'徐阶',zhangjuzheng:'张居正',huzongxian:'胡宗宪',player:'你',narrator:'旁白'};
const statNames = {evidence:'账册证据',relief:'赈粮进度',security:'海防供给',authority:'皇权稳定',reform:'新政准备'};
function statLabel(key){const defs=state.bootstrap?.story?.statDefinitions||[];const item=Array.isArray(defs)?defs.find(d=>(d.id||d.key)===key):defs[key];return (typeof item==='string'?item:item?.label||item?.name)||statNames[key]||key;}
const safeRead = (key, fallback = null) => {try{return JSON.parse(localStorage.getItem(`${NS}.${key}`)) ?? fallback;}catch{return fallback;}};
const save = (key, value) => {try{localStorage.setItem(`${NS}.${key}`,JSON.stringify(value));}catch{}};
const state = {bootstrap:null,run:null,screen:'cover',busy:false,film:null,held:null,typed:0,timer:null,toastTimer:null,drawer:null,lastFocus:null,qteTimer:null,qteStarted:0,qteElapsed:0,qtePaused:0,played:new Set(),prefs:{sound:true,media:true,accessible:true,...safeRead('preferences',{})},error:'',draft:'',textBeat:null};
const bgm = new Audio('/assets/title_bgm_5s_2m.m4a');
bgm.loop = true; bgm.preload = 'none'; bgm.volume = .2;
let unlocked = false;
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const display = value => Array.isArray(value) ? value.join('；') : typeof value === 'object' && value ? (value.text || value.label || '') : value ?? '';
const cast = () => {const list=state.bootstrap?.characters?.characters || state.bootstrap?.characters || [];return list.some(c=>c.id==='player')?list:[...list,{id:'player',name:'你',role:'这一局的执笔人',portrait:'/assets/characters/player/player_base.png',goal:'你的处置，将决定这本账落在谁的案前，也决定哪些人能够熬过眼前这一关。'}];};
const person = id => cast().find(c=>c.id===id || c.name===id);
const personName = id => person(id)?.name || names[id] || id || '旁白';
const portrait = (id, emotion = 'base') => {const character=person(id);return character?.expressions?.[emotion] || character?.expressions?.base || character?.portrait || (names[id] && id !== 'narrator' ? `/assets/characters/${id}/${id}_base.png` : null);};
const scenes = () => state.bootstrap?.story?.scenes || [];
const isInteractive = beat => ['choice','free_input','agent-input','qte'].includes(beat?.type);
const isEnding = () => state.run?.status === 'ending' || state.run?.status === 'complete';
const runIdentity = () => `${state.run?.id}:${state.run?.revision}:${state.run?.beat?.id}`;
const getRun = data => data.run || data;
function toast(message){clearTimeout(state.toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');state.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3400);}
async function request(url, body){const res=await fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await res.json();}catch{throw Object.assign(new Error('暂时无法连接书案，请稍后重试。'),{status:res.status});}if(!res.ok)throw Object.assign(new Error(typeof data.detail==='string'?data.detail:data.error||'操作未完成，请重新读取当前进度。'),{status:res.status});return data;}
function saveCheckpoint(run){save('run',run.id);if(Array.isArray(run.actionLog)&&run.actionLog.length===run.revision)save(`checkpoint.${run.id}`,{id:run.id,contentVersion:run.contentVersion,revision:run.revision,actionLog:run.actionLog});}
async function restoreCheckpoint(id){const checkpoint=safeRead(`checkpoint.${id}`);if(!checkpoint||checkpoint.id!==id||typeof checkpoint.contentVersion!=='string'||!Array.isArray(checkpoint.actionLog)||checkpoint.actionLog.length!==checkpoint.revision)throw new Error('服务器上的存档已失，本机没有完整的动作记录可恢复。请手动另起一局。');const run=getRun(await request('/api/runs/restore',{contentVersion:checkpoint.contentVersion,actionLog:checkpoint.actionLog}));save(`played.${run.id}`,safeRead(`played.${id}`,[]));return run;}
function rememberPrefs(){save('preferences',state.prefs);syncSound();}
function syncSound(){if(state.film?.video)state.film.video.muted=!state.prefs.sound;bgm.volume=state.film?.video && !state.film.video.paused && state.prefs.sound ? .035 : .19;if(!unlocked || !state.prefs.sound || document.hidden){bgm.pause();return;}bgm.play().catch(()=>{});}
function unlockSound(){unlocked=true;syncSound();}
document.addEventListener('pointerdown',()=>{if(!unlocked)unlockSound();},{passive:true});
document.addEventListener('keydown',()=>{if(!unlocked)unlockSound();},{once:true});
function stopTyping(){clearInterval(state.timer);state.timer=null;}
function stopQte(){clearInterval(state.qteTimer);state.qteTimer=null;}
function clearFilm(){if(state.film){const v=state.film.video;v.onended=v.onerror=v.onplaying=v.onwaiting=v.onstalled=v.onloadeddata=null;v.pause();clearTimeout(state.film.watchdog);}if(state.held)state.held.video.pause();state.film=null;state.held=null;syncSound();}
function tearDown(){stopTyping();stopQte();clearFilm();}
function toggleSound(){state.prefs.sound=!state.prefs.sound;rememberPrefs();document.querySelectorAll('[data-action="sound"]').forEach(b=>{b.textContent=state.prefs.sound?'♪':'♩';b.setAttribute('aria-label',state.prefs.sound?'关闭声音':'开启声音');});toast(state.prefs.sound?'声音已开启':'声音已关闭');}
function topbar(){return `<header class="topbar"><button class="icon-button" data-action="home" aria-label="返回封面">‹</button><div class="top-title"><small>大明由你改写 · 风暴初夜</small><strong>${esc(state.run?.scene?.title || '一卷未完')}</strong></div><button class="icon-button" data-action="sound" aria-label="${state.prefs.sound?'关闭声音':'开启声音'}">${state.prefs.sound?'♪':'♩'}</button></header>`;}
function navigation(){return `<nav class="bottom-nav" aria-label="剧情工具"><button data-action="state"><b>◇</b>局势</button><button data-action="cast"><b>♙</b>人物</button><button data-action="history"><b>≡</b>回声</button><button data-action="settings"><b>☷</b>设置</button></nav>`;}
function chapterDots(){return `<div class="chapter-dots" aria-label="第 ${(state.run?.sceneIndex||0)+1} 场，共 ${scenes().length} 场">${scenes().map((_,i)=>`<i class="${i<(state.run?.sceneIndex||0)?'done':i===(state.run?.sceneIndex||0)?'current':''}"></i>`).join('')}</div>`;}
function renderCover(){tearDown();state.screen='cover';app.setAttribute('aria-busy','false');const saved=state.run || safeRead('run');app.innerHTML=`<section class="cover"><img class="cover-bg" src="/assets/poster.webp" alt=""/><div class="cover-top"><div class="brand"><span class="seal">明</span>回声剧场 · 交互影视</div><button class="icon-button" data-action="sound" aria-label="${state.prefs.sound?'关闭声音':'开启声音'}">${state.prefs.sound?'♪':'♩'}</button></div><div class="cover-cast" aria-hidden="true"><img class="cast-left" src="${portrait('yansong')}" alt=""/><img class="cast-right" src="${portrait('hairui')}" alt=""/><div class="cover-emperor-frame"><img src="${portrait('jiajing')}" alt=""/></div></div><div class="cover-title"><p class="cover-kicker">一 个 王 朝 的 众 生 与 抉 择</p><h1>大明<span>由你改写</span></h1><div class="cover-subtitle">风暴初夜</div><p class="cover-tagline">账上是银两，账下是人命。<br>这一笔，由你来落。</p></div><div class="cover-actions"><button class="primary" data-action="${!state.bootstrap?'retry':saved?'continue':'start'}" ${state.busy?'disabled':''}>${state.busy?'正在展卷…':!state.bootstrap?'重新连接书案':saved?'续写此局':'入局 · 从此刻改写'}<span>↗</span></button><div class="cover-links"><button class="plain" data-action="${saved?'start':'chapters'}">${saved?'另起一局':'六场风云'}</button><button class="plain" data-action="cast">入局前 · 识人</button><button class="plain" data-action="settings">演出设置</button></div>${state.error?`<p class="error-inline" role="alert">${esc(state.error)}</p>`:''}</div><div class="cover-foot" style="flex-wrap:wrap"><span>原版人物 · 状态分支</span><i></i><span>选择留下回声</span><i></i><span>约 15 分钟</span><i></i><a href="/classic/">原版名场面</a></div></section>`;bindCommon();}
async function startRun(){if(state.busy)return;state.busy=true;state.error='';renderCover();try{const run=getRun(await request('/api/runs',{}));state.played=new Set();save(`played.${run.id}`,[]);state.busy=false;setRun(run);}catch(e){state.busy=false;state.error=e.message;renderCover();}}
async function continueRun(){if(state.busy)return;const id=state.run?.id || safeRead('run');if(!id){state.error='本机还没有可续写的存档，请选择入局开始。';renderCover();return;}state.busy=true;state.error='';renderCover();try{let run;try{run=getRun(await request(`/api/runs/${encodeURIComponent(id)}`));}catch(e){if(e.status!==404)throw e;run=await restoreCheckpoint(id);}state.busy=false;setRun(run);}catch(e){state.busy=false;state.error=e.message;renderCover();}}
function setRun(run){stopTyping();stopQte();const previous=state.run;if(state.held && (!isInteractive(run.beat) || isInteractive(previous?.beat) && previous?.beat?.id!==run.beat?.id || previous?.scene?.id!==run.scene?.id || previous?.id!==run.id || isEnding()))clearFilm();state.run=run;state.screen='story';state.error='';state.busy=false;saveCheckpoint(run);state.played=new Set(safeRead(`played.${run.id}`,[]));state.typed=0;state.textBeat=null;state.draft='';state.qteElapsed=0;window.scrollTo({top:0,behavior:'instant'});renderRun();}
function mediaForRun(){const run=state.run;if(!run)return null;const beat=run.beat||{};const ending=run.ending;const shot=isEnding()?(ending?.shotId||'M07'):(beat.shotId || (beat.id===run.scene?.firstBeatId || beat.type==='scene-intro'?run.scene.shotId:null));if(!shot)return null;const data=state.bootstrap?.media?.assets||{};const asset=Array.isArray(data)?data.find(a=>a.id===shot||a.shotId===shot):data[shot];if(!asset || !asset.file || !['ready','approved-runtime','provisional','technical-ready'].includes(asset.status||asset.runtimeStatus))return null;return {...asset,shotId:shot};}
function updateRunTags(){if(state.run){app.dataset.runId=state.run.id;app.dataset.runRevision=state.run.revision;app.dataset.beatId=state.run.beat?.id||'';app.dataset.sceneId=state.run.scene?.id||'';}}
function renderRun(){updateRunTags();if(!state.run)return renderCover();const media=mediaForRun();if(media && state.prefs.media && !state.played.has(media.shotId)){playFilm(media);return;}if(isEnding())return renderEnding();renderStage();}
function receiptHTML(){const r=state.run.receipt;if(!r || (!r.text && !r.changes?.length))return '';return `<aside class="receipt" aria-label="本次选择的后果"><div class="receipt-head">你的选择 · 已留下回声</div>${r.text?`<p>${esc(r.text)}</p>`:''}${r.responseText?`<p class="receipt-response"><b>${esc(personName(r.responseSpeaker))}</b>：${esc(r.responseText)}</p>`:''}<div class="changes">${(r.changes||[]).map(c=>`<span class="change ${Number(c.delta)<0?'negative':''}">${esc(c.label||statLabel(c.key||c.id))} ${Number(c.delta)>0?'+':''}${esc(c.delta)}${c.value!==undefined?` → ${esc(c.value)}`:''}</span>`).join('')}</div></aside>`;}
function optionRequirement(option){if(option.disabled===true||option.enabled===false||option.available===false)return option.lockReason||option.reason||'当前条件尚未满足';for(const r of option.requires||[]){const value=state.run.state?.stats?.[r.stat];if(r.stat&&r.min!==undefined&&Number(value||0)<r.min)return `${statLabel(r.stat)}需达到 ${r.min}`;if(r.stat&&r.max!==undefined&&Number(value||0)>r.max)return `${statLabel(r.stat)}需不高于 ${r.max}`;if(r.flag&&r.equals!==undefined&&state.run.state?.flags?.[r.flag]!==r.equals)return '当前经历尚未满足';}return '';}
function renderChoices(beat){return `<div class="choices">${(beat.options||beat.choices||[]).map((o,i)=>{const locked=optionRequirement(o);return `<button class="choice ${locked?'locked':''}" data-option="${esc(o.id)}" ${locked||state.busy?'disabled':''}><span class="choice-index">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(o.label||o.text)}</strong>${o.consequence||o.description||locked?`<small>${esc(locked||o.consequence||o.description)}</small>`:''}</span><span class="choice-arrow">${locked?'⌑':'›'}</span></button>`;}).join('')}</div>`;}
function renderInput(beat){const proposal=state.run.proposal;return `<div class="composer"><label class="screen-reader" for="free-text">你的话</label><textarea id="free-text" maxlength="${Math.min(600,Math.max(1,Number(beat.maxLength)||120))}" placeholder="${esc(beat.placeholder||'把你的打算说清楚……')}" ${state.busy?'disabled':''}>${esc(state.draft)}</textarea><button class="primary" data-action="preview" ${state.busy?'disabled':''}>${state.busy?'听取回应…':'说出你的打算'}</button><p class="input-hint">先听对方如何回应，再决定是否照此行动。</p></div>${proposal?`<section class="proposal"><small>对方听懂了你的意思</small><h3>${esc(proposal.label)}</h3><p>${esc(proposal.responseText)}</p><button class="primary" data-confirm-rule="${esc(proposal.ruleId)}">就按这个办法办</button><button class="plain" data-action="rewrite">我再想想</button></section>`:''}${beat.rules?.length?`<details class="notice"><summary>看看可以怎么说</summary><p>${beat.rules.map(r=>esc(r.label)).join(' · ')}</p></details>`:''}`;}
function renderQte(beat){return `<button class="qte-target" data-action="qte-success">${esc(beat.actionLabel||'按住账册')}</button>${state.prefs.accessible?'<p class="qte-note">从容模式 · 不限时<br>点击上方完成动作，继续写下你的选择。</p>':`<div class="qte-meter" aria-hidden="true"><i></i></div><p class="qte-note" id="qte-note">把握时机，完成动作。</p>`}<div class="qte-controls"><button class="plain" data-action="qte-accessible">${state.prefs.accessible?'切换计时挑战':'切换不限时操作'}</button><button class="plain" data-action="qte-failure">放开手</button></div>`;}
function renderStage(){updateRunTags();const run=state.run,beat=run.beat||{},interactive=isInteractive(beat);const stagePerson=beat.speaker && portrait(beat.speaker)?beat.speaker:({S000:'jiajing',S001:'hairui',S002:'yansong',S003:'jiajing',S004:'huzongxian',S005:'player'}[run.scene?.id]||'player');const p=portrait(stagePerson,beat.type==='dialogue'?(beat.emotion||'base'):'base');const media=mediaForRun();const held=interactive&&state.held;const background=run.scene?.background||'/assets/jiajing-scene.png';app.innerHTML=`<section class="stage ${interactive?'decision-mode':''} ${!p?'no-portrait':''} ${held?'held-stage':''}">${!held?`<img class="stage-bg" src="${esc(background)}" alt=""/>${p?`<img class="stage-portrait ${stagePerson==='jiajing'?'jiajing-photo':''} ${beat.type==='dialogue'?'':'scene-figure'}" src="${esc(p)}" alt="${esc(personName(stagePerson))}"/>`:''}`:''}${topbar()}${chapterDots()}<div class="scene-location"><span>${esc(run.scene?.location || '嘉靖年间')}</span>${media?`<button class="media-badge" data-action="replay-media">↻ 重看演出</button>`:`<button class="media-badge" data-action="chapters">${String((run.sceneIndex||0)+1).padStart(2,'0')} / ${String(scenes().length).padStart(2,'0')}</button>`}</div><div class="scene-spacer"></div>${receiptHTML()}${interactive?`<section class="decision"><p class="decision-label">${beat.type==='qte'?'此刻 · 掌握在你手里':beat.type==='free_input'?'你的话 · 你的立场':'这一笔 · 由你来落'}</p><div class="decision-context">${esc(beat.text)}</div>${beat.type==='choice'?renderChoices(beat):beat.type==='qte'?renderQte(beat):renderInput(beat)}${state.error?`<p class="error-inline" role="alert">${esc(state.error)}</p>`:''}</section>`:`<section class="reading-card"><div class="speaker">${esc(personName(beat.speaker))}${beat.type==='narration'?'<small>这一刻的风声</small>':''}</div><p class="story-text" id="story-text"></p><div class="reading-footer"><span class="read-hint">点击正文显示全部</span><button class="continue-button" data-action="advance" ${state.busy?'disabled':''}>${state.busy?'落笔中':'继续'}<span>›</span></button></div>${state.error?`<p class="error-inline" role="alert">${esc(state.error)}</p>`:''}</section>`}${navigation()}</section>`;if(held)app.firstElementChild.prepend(state.held.video);bindCommon();document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>act({type:'choose',optionId:b.dataset.option}));$('[data-confirm-rule]')?.addEventListener('click',e=>act({type:'choose',optionId:e.currentTarget.dataset.confirmRule}));$('#free-text')?.addEventListener('input',e=>state.draft=e.target.value);if(!interactive)typeText(beat);if(beat.type==='qte'&&!state.prefs.accessible)startQte(beat);}
function typeText(beat){stopTyping();const text=String(beat.text||'');const chars=Array.from(text);if(state.textBeat!==beat.id){state.typed=0;state.textBeat=beat.id;}if(matchMedia('(prefers-reduced-motion: reduce)').matches)state.typed=chars.length;const update=()=>{const el=$('#story-text');if(!el)return stopTyping();el.textContent=chars.slice(0,state.typed).join('');el.classList.toggle('complete',state.typed>=chars.length);if(state.typed>=chars.length)stopTyping();};update();if(state.typed<chars.length)state.timer=setInterval(()=>{state.typed=Math.min(chars.length,state.typed+2);update();},28);$('#story-text').onclick=()=>{state.typed=chars.length;update();};}
function startQte(beat){stopQte();const duration=Math.max(3000,Number(beat.durationMs||8000));state.qteStarted=performance.now();const identity=runIdentity();state.qteTimer=setInterval(()=>{if(document.hidden||state.drawer)return;if(identity!==runIdentity())return stopQte();const elapsed=state.qteElapsed+performance.now()-state.qteStarted;const remaining=Math.max(0,1-elapsed/duration);$('.qte-meter i')?.style.setProperty('--left',remaining);if(remaining<=0){stopQte();act({type:'qte',outcome:'failure'});}},40);}
async function act(action){if(state.busy||!state.run)return;const identity=runIdentity();state.busy=true;state.error='';stopTyping();stopQte();const requestId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;document.querySelectorAll('.choice,.continue-button,.composer .primary,.proposal .primary,.qte-target').forEach(b=>b.disabled=true);try{const result=getRun(await request(`/api/runs/${encodeURIComponent(state.run.id)}/act`,{...action,revision:state.run.revision,requestId}));if(runIdentity()!==identity)return;if(action.type==='free_input'){state.run=result;saveCheckpoint(result);state.busy=false;renderStage();return;}clearFilm();setRun(result);}catch(e){if(runIdentity()!==identity)return;state.busy=false;state.error=e.message;toast(e.message);try{const fresh=getRun(await request(`/api/runs/${encodeURIComponent(state.run.id)}`));state.run=fresh;saveCheckpoint(fresh);}catch{}renderRun();}}
function markPlayed(shot){state.played.add(shot);save(`played.${state.run.id}`,[...state.played]);}
function playFilm(media){stopTyping();stopQte();clearFilm();const identity=runIdentity(),runId=state.run.id;const video=document.createElement('video');video.className='film';video.src=media.file;video.playsInline=true;video.preload='auto';video.muted=!state.prefs.sound;video.controls=false;video.setAttribute('aria-label',state.run.scene?.title||'剧情演出');if(media.subtitleFile){const track=document.createElement('track');Object.assign(track,{kind:'subtitles',srclang:'zh',label:'中文',default:true,src:media.subtitleFile});video.append(track);}const film={video,media,identity,runId,finished:false,watchdog:null};state.film=film;app.innerHTML=`<section class="film-stage">${topbar()}<div class="film-fallback" id="film-fallback"><p>影像正在展开…</p></div><div class="film-controls"><small>${esc(isEnding()?'卷终回声':(media.shotId===state.run.scene?.shotId && state.run.scene?.mediaCaption)||state.run.scene?.location||'嘉靖年间')}</small><h2>${esc(isEnding()?state.run.ending?.title:state.run.scene?.title)}</h2><div class="film-control-row"><button data-action="film-text">切换图文</button><button data-action="film-skip">跳过演出 ›</button></div></div></section>`;app.firstElementChild.prepend(video);bindCommon();const valid=()=>state.film===film&&!film.finished&&runIdentity()===identity;const fallback=(label,retry=false)=>{if(!valid())return;$('#film-fallback').innerHTML=`<p>${esc(label)}</p><button class="primary" id="film-play">${retry?'重新加载演出':'播放演出'}</button>`;$('#film-play').onclick=()=>{if(retry)video.load();start();};};const start=()=>{if(!valid())return;video.play().then(()=>{if(valid())$('#film-fallback').innerHTML='';syncSound();}).catch(()=>fallback('点击开启这一段声画。'));};video.onplaying=()=>{if(!valid())return;clearTimeout(film.watchdog);$('#film-fallback').innerHTML='';syncSound();};video.onended=()=>{if(valid())finishFilm(true);};video.onerror=()=>fallback('这段影像暂时未能载入，可重试或继续图文。',true);video.onwaiting=video.onstalled=()=>{clearTimeout(film.watchdog);film.watchdog=setTimeout(()=>fallback('影像加载较慢，可重试或切换图文。',true),12000);};film.watchdog=setTimeout(()=>fallback('影像加载较慢，可重试或切换图文。',true),12000);start();}
function finishFilm(preserve){const film=state.film;if(!film||film.finished)return;film.finished=true;clearTimeout(film.watchdog);const v=film.video;v.onended=v.onerror=v.onplaying=v.onwaiting=v.onstalled=null;v.pause();v.muted=true;markPlayed(film.media.shotId);state.film=null;if(preserve&&isInteractive(state.run.beat)&&v.readyState>=2&&v.videoWidth){v.className='held-film';v.setAttribute('aria-hidden','true');v.removeAttribute('autoplay');for(const t of v.textTracks)t.mode='disabled';if(Number.isFinite(v.duration)&&v.duration>.1)v.currentTime=Math.max(0,v.duration-.04);state.held={video:v};}else state.held=null;syncSound();renderRun();}
function renderEnding(){clearFilm();stopTyping();const ending=state.run.ending||{};const settlement=ending.settlement||[];app.innerHTML=`<section class="ending-stage"><img class="ending-art" src="/assets/poster.webp" alt=""/><div class="cover-top"><span class="seal">卷</span><button class="plain" data-action="home">返回封面</button></div><p class="ending-kicker">一卷已成 · 余声未尽</p><h1>${esc(ending.title||'落笔有声')}</h1><div class="ending-divider">◇</div><p class="ending-copy">${esc(ending.text||'你做过的选择，已留在这个风云交汇的夜晚。')}</p>${receiptHTML()}<section class="ending-summary"><h3>此局留痕</h3>${settlement.length?`<ul>${settlement.map(item=>`<li>${esc(display(item))}</li>`).join('')}</ul>`:''}<div class="changes">${Object.entries(state.run.state?.stats||{}).map(([k,v])=>`<span class="change">${esc(statLabel(k))} ${esc(v)}</span>`).join('')}</div></section><div class="ending-actions"><button class="primary" data-action="start">重开一卷 · 看另一种可能<span>↗</span></button><button class="plain" data-action="history">翻阅这一局的回声</button>${mediaForRun()?'<button class="plain" data-action="replay-media">重看卷终演出</button>':''}</div>${navigation()}</section>`;bindCommon();}
function definitions(){const defs=state.bootstrap.story.statDefinitions||{};return Array.isArray(defs)?defs:Object.entries(defs).map(([key,d])=>typeof d==='object'?{key,...d}:{key,label:d});}
function stateSheet(){const stats=state.run?.state?.stats||{};return `<p class="sheet-eyebrow">眼前局势 · 每一笔都算数</p>${Object.keys(stats).length?definitions().map(d=>{const key=d.key||d.id;const value=Number(stats[key]||0),max=Number(d.max||100);return `<div class="stat-row"><div class="stat-label"><span>${esc(d.label||d.name||statLabel(key))}</span><b>${value}</b></div><div class="stat-track"><i style="width:${Math.max(0,Math.min(100,value/max*100))}%"></i></div>${d.description?`<p class="stat-description">${esc(d.description)}</p>`:''}</div>`;}).join(''):'<p class="empty-note">入局后，账册、赈粮、海防与朝局的变化，会在这里一一记下。</p>'}<p class="notice">数值只由你实际完成的行动改变。重看演出与切换图文，不会重复改变这一局。</p>`;}
function castSheet(){return `<p class="sheet-eyebrow">六个人 · 六种天下</p><div class="cast-grid">${cast().map(c=>`<button class="cast-card" data-character="${esc(c.id)}"><img src="${esc(c.portrait||portrait(c.id))}" alt="${esc(c.name)}" loading="lazy"/><div class="cast-card-copy"><strong>${esc(c.name)}</strong><small>${esc(c.role||c.title||c.dao)}</small></div></button>`).join('')}</div>`;}
function characterSheet(id){const c=person(id);if(!c)return '<p>人物尚未登场。</p>';const relation=state.run?.state?.relationships?.[id];const relValue=typeof relation==='object'?Object.entries(relation).map(([k,v])=>`${k} ${v}`).join(' · '):relation;return `<div class="cast-bio-top"><img src="${esc(c.portrait||portrait(id))}" alt="${esc(c.name)}"/></div><div class="cast-bio-title"><h3>${esc(c.name)}</h3><p>${esc(c.role||'')}${c.dao?`<br>${esc(c.dao)}`:''}</p></div><div class="relationship-card"><strong>${relValue!==undefined?`与你的关系 · ${esc(relValue)}`:'尚未结下这一局的因果'}</strong><small>只记录本局已经发生的往来。</small></div>${c.goal?`<p class="section-label">他在意什么</p><p class="bio-copy">${esc(c.goal)}</p>`:''}${c.redLines?.length?`<p class="section-label">他不会轻易让步的事</p><ul class="bio-list">${c.redLines.map(t=>`<li>${esc(display(t))}</li>`).join('')}</ul>`:''}${c.belief?`<p class="section-label">行事准则</p><p class="bio-copy">${esc(c.belief)}</p>`:''}${c.resources?.length?`<p class="section-label">手中的筹码</p><p class="bio-copy">${esc(c.resources.join('；'))}</p>`:''}<button class="plain" data-action="cast">‹ 返回人物册</button>`;}
function historySheet(){const history=state.run?.history||[];const memories=state.run?.state?.memories||[];const m=Array.isArray(memories)?memories:Object.entries(memories).map(([key,value])=>typeof value==='object'?{key,...value}:{key,text:value});return `<p class="sheet-eyebrow">你做过的选择，会被记住</p>${m.length?`<p class="section-label">此局记忆</p>${m.map((item,i)=>`<article class="memory-item"><small>回声 ${String(i+1).padStart(2,'0')}</small><p>${esc(display(item))}</p></article>`).join('')}`:''}<p class="section-label">行事记录</p>${history.length?history.map((item,i)=>`<article class="memory-item"><small>${esc(item.sceneTitle||item.sceneId||`第 ${i+1} 笔`)}</small><h3>${esc(item.action||item.label||item.choiceLabel||item.optionLabel||item.actionLabel||item.text||'你留下了一次选择')}</h3>${item.responseText||item.consequence?`<p>${esc(item.responseText||item.consequence)}</p>`:''}</article>`).join(''):'<p class="empty-note">还没有落下第一笔。<br>往后的抉择与故人回应，将会记在这里。</p>'}`;}
function chaptersSheet(){return `<p class="sheet-eyebrow">风暴初夜 · 六场风云</p><ol class="chapter-list">${scenes().map((s,i)=>`<li><em>${String(i+1).padStart(2,'0')}</em><div><strong>${esc(s.title)}</strong><small>${esc(s.location)}</small></div>${state.run&&i===state.run.sceneIndex?'<span class="now">此刻</span>':''}</li>`).join('')}</ol><p class="notice">顺着你的选择走下去。不同的处理，会在同一条路上留下不同的回声。</p>`;}
function settingsSheet(){return `<div class="setting-row"><div><strong>剧情演出</strong><p>有声影像与图文阅读，沿用同一份进度。</p></div><button class="toggle ${state.prefs.media?'on':''}" data-pref="media">${state.prefs.media?'声画':'图文'}</button></div><div class="setting-row"><div><strong>声音</strong><p>演出原声响起时，背景乐会自动放轻。</p></div><button class="toggle ${state.prefs.sound?'on':''}" data-pref="sound">${state.prefs.sound?'开启':'关闭'}</button></div><div class="setting-row"><div><strong>从容操作</strong><p>关键动作不限时，点击即可完成。</p></div><button class="toggle ${state.prefs.accessible?'on':''}" data-pref="accessible">${state.prefs.accessible?'开启':'关闭'}</button></div><p class="notice">游玩进度自动保存于此设备。人物回应和选择后果，以本局已知的事实为准。</p>`;}
function openSheet(kind,id){state.lastFocus=document.activeElement;if(state.run?.beat?.type==='qte'&&state.qteTimer){state.qteElapsed+=performance.now()-state.qteStarted;stopQte();}state.drawer={kind,id};const title={state:'朝局账本',cast:'人物册',character:'人物册',history:'此局回声',settings:'演出设置',chapters:'卷中六场'}[kind];const contents={state:stateSheet,cast:castSheet,character:()=>characterSheet(id),history:historySheet,settings:settingsSheet,chapters:chaptersSheet};overlay.innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="${title}"><header class="sheet-head"><h2>${title}</h2><button class="sheet-close" aria-label="关闭">×</button></header>${contents[kind]()}</section></div>`;$('.sheet-close').onclick=closeSheet;$('.sheet-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet();};overlay.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>openSheet('character',b.dataset.character));overlay.querySelectorAll('[data-action="cast"]').forEach(b=>b.onclick=()=>openSheet('cast'));overlay.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{const key=b.dataset.pref;state.prefs[key]=!state.prefs[key];rememberPrefs();if(key==='media'&&state.film)finishFilm(false);openSheet('settings');});$('.sheet-close').focus();}
function closeSheet(){const refresh=state.drawer?.kind==='settings';state.drawer=null;overlay.innerHTML='';state.lastFocus?.focus?.();if(refresh&&state.screen==='story'&&!state.film)renderRun();else if(state.run?.beat?.type==='qte'&&!state.prefs.accessible&&state.screen==='story'&&!state.film)startQte(state.run.beat);}
document.addEventListener('keydown',e=>{if(!state.drawer)return;if(e.key==='Escape'){e.preventDefault();closeSheet();}if(e.key==='Tab'){const list=[...overlay.querySelectorAll('button:not([disabled]),textarea,a[href],input')];const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
function bindCommon(){app.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.action;if(action==='retry')return boot();if(action==='sound')return toggleSound();if(action==='start')return startRun();if(action==='continue')return continueRun();if(action==='home'){closeSheet();return renderCover();}if(['state','cast','history','settings','chapters'].includes(action))return openSheet(action);if(action==='advance'){const chars=Array.from(state.run.beat.text||'');if(state.typed<chars.length){state.typed=chars.length;typeText(state.run.beat);return;}return act({type:'advance'});}if(action==='preview'){const text=$('#free-text')?.value.trim();if(!text)return toast('先写下你的打算。');state.draft=text;return act({type:'free_input',text});}if(action==='rewrite'){state.run.proposal=null;renderStage();return $('#free-text')?.focus();}if(action==='qte-success')return act({type:'qte',outcome:'success'});if(action==='qte-failure')return act({type:'qte',outcome:'failure'});if(action==='qte-accessible'){state.prefs.accessible=!state.prefs.accessible;rememberPrefs();state.qteElapsed=0;return renderStage();}if(action==='replay-media'){const media=mediaForRun();if(media)return playFilm(media);}if(action==='film-skip')return finishFilm(true);if(action==='film-text'){state.prefs.media=false;rememberPrefs();return finishFilm(false);}});}
document.addEventListener('visibilitychange',()=>{if(document.hidden){bgm.pause();state.film?.video.pause();if(state.qteTimer){state.qteElapsed+=performance.now()-state.qteStarted;stopQte();}}else{syncSound();if(state.film){const v=state.film.video;v.play().catch(()=>{const panel=$('#film-fallback');if(panel){panel.innerHTML='<p>继续这一段声画</p><button class="primary" id="resume-film">继续播放</button>';$('#resume-film').onclick=()=>v.play().then(()=>panel.innerHTML='').catch(()=>{});}});}if(state.run?.beat?.type==='qte'&&!state.prefs.accessible&&!state.drawer&&state.screen==='story')startQte(state.run.beat);}});
window.addEventListener('pagehide',()=>{tearDown();bgm.pause();});
async function boot(){state.busy=true;renderCover();try{state.bootstrap=await request('/api/bootstrap');state.busy=false;state.error='';app.setAttribute('aria-busy','false');renderCover();}catch(e){state.busy=false;state.error='剧情档案暂未连接，请稍后重新展卷。';renderCover();}}
boot();
setInterval(async()=>{if(document.hidden||state.film||!state.bootstrap)return;try{const data=await request('/api/bootstrap');state.bootstrap.media=data.media;if(state.screen==='story'&&!state.busy&&!state.drawer){const media=mediaForRun();if(media&&state.prefs.media&&!state.played.has(media.shotId))renderRun();}}catch{}},30000);
